---
title: "The Power of Efficiency"
author: "Sal Gutierrez"
format: 
  html: 
    self-contained: true
layout: margin-left
editor: visual
execute: 
  eval: false
  echo: true
---

<!-- As we’ve said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term “efficiency” means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Include: What is the definition of “efficiency”? What does efficiency look like in statistical computing / data science? What does efficiency allow you to do? Why is efficiency important? Where did you encounter efficiency, and what were some “a-ha” moments you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.) -->

If you ask Google, efficiency is to be [capable of producing desired results with little or no waste](https://www.merriam-webster.com/dictionary/efficient). My definition falls along those lines which is to think of ways to save time for yourself, as well as your computer when trying to solve a problem or completing some analysis of your data. I do want to make an emphasis on that efficiency does not only apply for your code, but also the time you spend writing that code. Even if you are a slow typer, there are coding practices that will save you time like writing functions to reduce code duplication, or simple function calls that reduce redundancy.

Efficiency is extremely important in Data Science because more often than not, you will be working with massive files or unimaginable size. Yes, so far we have been working with pretty tiny CSV files, but in industry, and for example, a company could have millions of records of customers which would inherently make a CSV file with all these records extremely large. Even if you can shave off a few milliseconds per record, that could mean minutes, or hours saved when processing data.

This is why efficiency is important. As the famous quote says: "time is money" which is very true in industry. What if you have a system that collects daily data, computes some analysis on this data, and then sends a report to stakeholders early in the morning. What if this report is highly valuable and important, then it would be terrible if it would take you hours to generate this report because other people depend on it. Efficiency allows you to be quick when solving a problem. Nobody likes to wait for a long time for a problem to be solved.

I had an "aha" moment very early on in the quarter. We were using annotations on a plot to remove the need of a legend on the y-axis. This required us to add an individual annotation to each class we were plotting. However, I thought: "wow this is very time consuming" so I thought of using a geom_text() plot on top of the density plot to take care of the annotations. I didn't save hours on computation but I realized that there are better ways to do things in R. This made me feel more confident later in the quarter to take the initiative to learn functions before they were taught and use kables to display nice tables in my documents.
